# version: "3.8"

# services:
#   frontend:
#     build:
#       context: .
#     ports:
#       - "8080:8080"
  # front_gateway:
  #   build: ./Bingo/nginx
  #   ports:
  #     - 80:80
version: "3.3"

secrets:
  db_password:
    external: true

services:
  frontend:
    container_name: frontend
    build:
      context: ./Bingo
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
  front_gateway:
    build: ./Bingo/nginx
    ports:
      - 80:80

  backend:
    environment:
      JWT_SECRET: 12345
      MONGODB_URL: mongodb://root:example@mongo:27017
      PASSWORD_SALT: qwerty
  mongo:
    build:
      secrets:
      - db_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



